= RHEL In-place Upgrade Automation Workshop

This workshop will introduce a comprehensive approach to automate
in-place upgrades for Red Hat Enterprise Linux (RHEL). The solution uses
Ansible Automation Platform (AAP) to execute upgrades at enterprise
scale across a large estate of RHEL hosts. The workshop demonstrates how
to use an example of this approach to perform upgrades from RHEL7 to
RHEL8, RHEL8 to RHEL9, and from RHEL9 to RHEL10. You will also learn about how this
solution can be customized to meet the special requirements of your
enterprise environment.

There are four key features that the solution approach recommends to
deliver success at scale:

image::ripu_key_features.svg[Automate Everything, Snapshot/rollback, Custom Modules, Reporting Dashboard,link=self,window=blank]

As you progress through this workshop, you will learn more about the
importance of these features and the different options for how you might
implement them in your enterprise. For this workshop, we assume you have
at least some experience using Ansible Automation Platform and working
with Ansible playbooks and roles. If you're new to Ansible, consider
first completing the workshop
https://labs.demoredhat.com/exercises/ansible_rhel[Ansible for Red Hat
Enterprise Linux^].

== Presentations

The exercises are self explanatory and guide the participants through
all the phases of an automated RHEL in-place upgrade. All concepts are
explained as they are introduced.

There is an optional presentation deck available with additional
information on the benefits of the approach demonstrated in this
workshop: <WIP - Deck link to be added>.

== Time Planning

The time required to complete the workshop depends on the number of
participants and how familiar they are with Linux and Ansible. This abbreviated version of the workshop can be completed in under 2 hours.

As this lab does have several long-running tasks, like the O/S upgrade, when working with a group of participants, it is recommended to keep the group together to have discussion time and presentations during those long-running tasks.  A recommended schedule is:

<WIP - schedule to be added>

== Lab Diagram

The lab consists of an Ansible Automation Platform (AAP) control host and
three RHEL pet application hosts, one each for RHEL7, RHEL8, and RHEL9.
These pet app hosts are where we will be performing the RHEL in-place
upgrades. The AAP control host is used to run the Ansible playbook and
workflow jobs that automate the RHEL in-place upgrade process.

== Workshop Exercises

The workshop is composed of three sections each of which includes a
number of exercises. Each exercise builds upon the steps performed and
concepts learned in the previous exercises, so it is important to do
them in the prescribed order.

=== Section 1 - Pre-upgrade Analysis

* xref:1.1-setup/README.adoc[Exercise 1.1 - Workshop Lab Environment]
* xref:1.2-preupg/README.adoc[Exercise 1.2 - Run Pre-upgrade Jobs]
* xref:1.3-report/README.adoc[Exercise 1.3 - Review Pre-upgrade Reports]
* xref:1.4-remediate/README.adoc[Exercise 1.4 - Perform Recommended Remediation]
* xref:1.5-custom-modules/README.adoc[Exercise 1.5 - Custom Pre-upgrade Checks]

=== Section 2 - RHEL OS Upgrade

* xref:2.1-upgrade/README.adoc[Exercise 2.1 - Run OS Upgrade Jobs]
* xref:2.2-snapshots/README.adoc[Exercise 2.2 - Let's Talk About Snapshots]
* xref:2.3-check-upg/README.adoc[Exercise 2.3 - Check if the Upgrade Worked]

=== Section 3 - Rolling Back
NOTE: The hands-on portion of this section is currently disabled due to lab environment limitations.
* xref:3.1-rm-rf/README.adoc[Exercise 3.1 - (Optional) Trash the Instance]
* xref:3.2-rollback/README.adoc[Exercise 3.2 - Run Rollback Job]
* xref:3.3-check-undo/README.adoc[Exercise 3.3 - Check if Upgrade Undone]
* xref:3.4-conclusion/README.adoc[Exercise 3.4 - Rinse and Repeat]

== Workshop Navigation

Your will find links to the previous and next exercises at the bottom of
each exercise page. Click the link below to get started.
