= RHEL In-place Upgrade Automation Workshop

This workshop will introduce a comprehensive approach to automate
in-place upgrades for Red Hat Enterprise Linux (RHEL). The solution uses
Ansible Automation Platform (AAP) to execute upgrades at enterprise
scale across a large estate of RHEL hosts. The workshop demonstrates how
to use an example of this approach to perform upgrades from RHEL7 to
RHEL8 and from RHEL8 to RHEL9. You will also learn about how this
solution can be customized to meet the special requirements of your
enterprise environment.

There are four key features that the solution approach recommends to
deliver success at scale:

image::ripu_key_features.svg[Automate Everything, Snapshot/rollback, Custom Modules, Reporting Dashboard]

As you progress through this workshop, you will learn more about the
importance of these features and the different options for how you might
implement them in your enterprise. For this workshop, we assume you have
at least some experience using Ansible Automation Platform and working
with Ansible playbooks and roles. If you’re new to Ansible, consider
first completing the workshop
https://labs.demoredhat.com/exercises/ansible_rhel[Ansible for Red Hat
Enterprise Linux].

== Table of Contents

* link:#rhel-in-place-upgrade-automation-workshop[RHEL In-place Upgrade
Automation Workshop]
** link:#table-of-contents[Table of Contents]
** link:#presentations[Presentations]
** link:#time-planning[Time Planning]
** link:#lab-diagram[Lab Diagram]
** link:#workshop-exercises[Workshop Exercises]
*** link:#section-1---pre-upgrade-analysis[Section 1 - Pre-upgrade Analysis]
*** link:#section-2---rhel-os-upgrade[Section 2 - RHEL OS Upgrade]
*** link:#section-3---rolling-back[Section 3 - Rolling Back]
** link:#workshop-navigation[Workshop Navigation]

== Presentations

The exercises are self explanatory and guide the participants through
all the phases of an automated RHEL in-place upgrade. All concepts are
explained as they are introduced.

There is an optional presentation deck available with additional
information on the benefits of the approach demonstrated in this
workshop: link:../../decks/ansible_ripu.pdf[RHEL In-place Upgrade
Automation]

== Time Planning

The time required to complete the workshop depends on the number of
participants and how familiar they are with Linux and Ansible. The
exercises themselves should take a minimum of 4 hours. The introduction
in the optional presentation adds another hour. There are also some
optional exercises which can be skipped, but are recommended if time
allows. There are also supplemental exercises at the end of the workshop
to allow for open-ended experimentation and exploring customizations
that may apply to your specific environment and requirements. The lab
environment provisioned could even be used for a multi-day deep dive
workshop, but that is beyond the scope of this guide.

== Lab Diagram

The lab environment provisioned for the workshop includes a number of
RHEL cloud instances. One instance is dedicated to hosting AAP and is
used to run playbook and workflow jobs. The jobs are executed against
the remaining hosts which will be upgraded in-place to the next RHEL
major version. The automation uses LVM to manage the snapshot/rollback
capability.

image::ripu_lab_diagram.svg[RHEL In-place Upgrade Automation Workshop lab diagram]

== Workshop Exercises

The workshop is composed of three sections each of which includes a
number of exercises. Each exercise builds upon the steps performed and
concepts learned in the previous exercises, so it is important to do
them in the prescribed order.

=== Section 1 - Pre-upgrade Analysis

* xref:1.1-setup/README.adoc[Exercise 1.1 - Workshop Lab Environment]
* xref:1.2-preupg/README.adoc[Exercise 1.2 - Run Pre-upgrade Jobs]
* xref:1.3-report/README.adoc[Exercise 1.3 - Review Pre-upgrade Reports]
* xref:1.4-remediate/README.adoc[Exercise 1.4 - Perform Recommended Remediation]
* xref:1.5-custom-modules/README.adoc[Exercise 1.5 - Custom Pre-upgrade Checks]
* xref:1.6-my-pet-app/README.adoc[Exercise 1.6 - Deploy a Pet App]

=== Section 2 - RHEL OS Upgrade

* xref:2.1-upgrade/README.adoc[Exercise 2.1 - Run OS Upgrade Jobs]
* xref:2.2-snapshots/README.adoc[Exercise 2.2 - Let’s Talk About Snapshots]
* xref:2.3-check-upg/README.adoc[Exercise 2.3 - Check if the Upgrade Worked]
* xref:2.4-check-pet-app/README.adoc[Exercise 2.4 - (Optional) How is the Pet App Doing?]

=== Section 3 - Rolling Back

* xref:3.1-rm-rf/README.adoc[Exercise 3.1 - (Optional) Trash the Instance]
* xref:3.2-rollback/README.adoc[Exercise 3.2 - Run Rollback Job]
* xref:3.3-check-undo/README.adoc[Exercise 3.3 - Check if Upgrade Undone]
* xref:3.4-conclusion/README.adoc[Exercise 3.4 - Rinse and Repeat]

== Workshop Navigation

Your will find links to the previous and next exercises at the bottom of
each exercise page. Click the link below to get started.

'''''

*Navigation*

xref:1.1-setup/README.adoc[Next Exercise]
